<?php

namespace Ner0tic\FoursquareBundle\Curl\Manager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-03 at 18:40:06.
 */
class CurlManagerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CurlManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CurlManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Manager\CurlManager::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Manager\CurlManager::__isset
     * @todo   Implement test__isset().
     */
    public function test__isset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
