<?php

namespace Ner0tic\FoursquareBundle\Curl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-03 at 18:40:06.
 */
class CurlTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Curl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Curl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Curl::addCurl
     * @todo   Implement testAddCurl().
     */
    public function testAddCurl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Curl::getResult
     * @todo   Implement testGetResult().
     */
    public function testGetResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Curl::getSequence
     * @todo   Implement testGetSequence().
     */
    public function testGetSequence() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Curl::getTimers
     * @todo   Implement testGetTimers().
     */
    public function testGetTimers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ner0tic\FoursquareBundle\Curl\Curl::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
